<?php
/**
 * PRDRWNDN® Theme — functions.php
 *
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *  DO NOT EDIT THIS FILE DIRECTLY.
 *  Make all your changes in the CHILD THEME instead:
 *  wp-content/themes/prdrwndn-theme-child/functions.php
 *
 *  If you edit this file, your changes will be lost
 *  the next time the theme is updated.
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *
 *  TABLE OF CONTENTS
 *  1. Theme Setup          — supports, menus, image sizes
 *  2. Enqueue Assets       — CSS and JS files
 *  3. WooCommerce          — wrappers, overrides
 *  4. Widget Areas         — sidebar registration
 *  5. Customizer           — live preview settings
 *  6. Helper Functions     — reusable template helpers
 *  7. PWA                  — manifest + service worker
 *  8. AJAX                 — cart count endpoint
 *  9. Gutenberg            — disable on custom templates
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Security: block direct file access


/* ════════════════════════════════════════════════════
   1. THEME SETUP
   Registers everything WordPress needs to know about
   this theme — features it supports, menu locations,
   and image sizes.
════════════════════════════════════════════════════ */
function prdrwndn_setup() {

    // Allow WordPress to manage the <title> tag automatically
    add_theme_support( 'title-tag' );

    // Enable featured images (thumbnails) on posts and pages
    add_theme_support( 'post-thumbnails' );

    // Use modern HTML5 markup for forms, galleries, etc.
    add_theme_support( 'html5', [
        'search-form', 'comment-form', 'comment-list',
        'gallery', 'caption', 'style', 'script'
    ] );

    // Allow a custom logo to be uploaded via Appearance → Customize → Site Identity
    add_theme_support( 'custom-logo', [
        'height'      => 60,
        'width'       => 200,
        'flex-width'  => true,
        'flex-height' => true,
    ] );

    // Tell WordPress this theme supports WooCommerce
    add_theme_support( 'woocommerce' );
    add_theme_support( 'wc-product-gallery-zoom' );      // pinch-to-zoom on product images
    add_theme_support( 'wc-product-gallery-lightbox' );  // lightbox on product images
    add_theme_support( 'wc-product-gallery-slider' );    // swipe gallery on product page

    // Register navigation menu locations
    // You assign actual menus to these in Appearance → Menus
    register_nav_menus( [
        'primary' => __( 'Primary Navigation (desktop header)', 'prdrwndn' ),
        'mobile'  => __( 'Mobile Navigation (hamburger menu)', 'prdrwndn' ),
        'footer'  => __( 'Footer Navigation', 'prdrwndn' ),
    ] );

    // Register an extra image size for product cards
    // Width × Height, true = hard crop (not proportional)
    add_image_size( 'prdrwndn-card', 600, 600, true );
    add_image_size( 'prdrwndn-hero', 1400, 900, true );
}
add_action( 'after_setup_theme', 'prdrwndn_setup' );


/* ════════════════════════════════════════════════════
   2. ENQUEUE ASSETS
   Loads all CSS and JavaScript files.
   Files load in this order:
   1. Google Fonts (external CDN)
   2. Parent theme stylesheet (style.css)
   3. Main JavaScript (assets/js/main.js)
   4. Shop JavaScript (only on WooCommerce pages)
════════════════════════════════════════════════════ */
function prdrwndn_assets() {
    // Theme version — change this in style.css to bust browser cache
    $v = wp_get_theme()->get( 'Version' );

    // Google Fonts — Bebas Neue (display), Cormorant Garamond (serif), Inter (body)
    // To change fonts: replace this URL with a new one from fonts.google.com
    wp_enqueue_style(
        'prdrwndn-fonts',
        'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400&family=Inter:wght@300;400;500;600;700&display=swap',
        [],
        null // null = no version (Google handles cache)
    );

    // Main stylesheet — all the theme's CSS
    wp_enqueue_style(
        'prdrwndn-style',
        get_stylesheet_uri(),
        [ 'prdrwndn-fonts' ], // loads after fonts
        $v
    );

    // Main JS — scroll reveal, mobile menu, header scroll, scent pills
    wp_enqueue_script(
        'prdrwndn-main',
        get_template_directory_uri() . '/assets/js/main.js',
        [], // no dependencies
        $v,
        true // load in footer (better performance)
    );

    // Shop JS — only loads on WooCommerce pages (shop, product, cart, checkout)
    // Handles live cart count updates after adding to cart
    if ( class_exists( 'WooCommerce' ) &&
         ( is_shop() || is_product() || is_product_category() || is_cart() || is_checkout() )
    ) {
        wp_enqueue_script(
            'prdrwndn-shop',
            get_template_directory_uri() . '/assets/js/shop.js',
            [ 'jquery' ], // needs jQuery (WooCommerce provides it)
            $v,
            true
        );
    }

    // Pass PHP data to JavaScript so JS can use WordPress URLs
    // Access these in JS as: prdrwndn.ajaxUrl, prdrwndn.cartUrl, etc.
    wp_localize_script( 'prdrwndn-main', 'prdrwndn', [
        'ajaxUrl' => admin_url( 'admin-ajax.php' ),  // WordPress AJAX endpoint
        'nonce'   => wp_create_nonce( 'prdrwndn_nonce' ), // security token
        'cartUrl' => class_exists('WooCommerce') ? wc_get_cart_url() : home_url('/cart/'),
        'appUrl'  => home_url( '/app.html' ),
        'siteUrl' => home_url(),
    ] );
}
add_action( 'wp_enqueue_scripts', 'prdrwndn_assets' );


/* ════════════════════════════════════════════════════
   3. WOOCOMMERCE WRAPPERS
   WooCommerce wraps its output in a default container.
   We remove the default one and replace it with ours
   so the shop pages use our theme's layout.
════════════════════════════════════════════════════ */

// Remove WooCommerce's default content wrappers
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content',  'woocommerce_output_content_wrapper_end', 10 );

// Add our own wrappers instead
add_action( 'woocommerce_before_main_content', function() {
    echo '<div class="woocommerce-content-wrap container"><div class="woo-main">';
} );
add_action( 'woocommerce_after_main_content', function() {
    echo '</div></div>';
} );

// Style WooCommerce breadcrumbs separator to match our theme
add_filter( 'woocommerce_breadcrumb_defaults', function( $defaults ) {
    $defaults['delimiter'] = ' &rsaquo; '; // › separator
    return $defaults;
} );

// Set the number of products shown per page on the shop
// Change the number 8 to however many you want
add_filter( 'loop_shop_per_page', function() {
    return 8;
} );


/* ════════════════════════════════════════════════════
   4. WIDGET AREAS
   Registers sidebar/widget areas you can fill in
   Appearance → Widgets.
════════════════════════════════════════════════════ */
function prdrwndn_widgets_init() {
    register_sidebar( [
        'name'          => __( 'Shop Sidebar', 'prdrwndn' ),
        'id'            => 'shop-sidebar',
        'description'   => __( 'Widgets shown beside the WooCommerce shop.', 'prdrwndn' ),
        'before_widget' => '<div class="widget %2$s">',
        'after_widget'  => '</div>',
        'before_title'  => '<h3 class="widget-title">',
        'after_title'   => '</h3>',
    ] );
}
add_action( 'widgets_init', 'prdrwndn_widgets_init' );


/* ════════════════════════════════════════════════════
   5. CUSTOMIZER
   All settings available in Appearance → Customize.
   Everything here can be changed live without editing
   any code files.

   Structure:
   Panel "PRDRWNDN® Theme"
   ├── Section: Branding      (tagline)
   ├── Section: Colors        (green, forest, cream, ink)
   ├── Section: Homepage      (hero text, product IDs, counts)
   └── Section: Footer        (footer description text)
════════════════════════════════════════════════════ */
function prdrwndn_customizer( $wp_customize ) {

    // ── Create the main panel that groups all our sections ──
    $wp_customize->add_panel( 'prdrwndn_panel', [
        'title'       => __( 'PRDRWNDN® Theme', 'prdrwndn' ),
        'description' => __( 'Customize your PRDRWNDN® store appearance.', 'prdrwndn' ),
        'priority'    => 10,
    ] );

    /* ── SECTION: Branding ── */
    $wp_customize->add_section( 'prdrwndn_branding', [
        'title'       => __( 'Branding', 'prdrwndn' ),
        'description' => __( 'Core brand messaging shown across the site.', 'prdrwndn' ),
        'panel'       => 'prdrwndn_panel',
    ] );

    // Hero tagline — the sentence below the main headline
    $wp_customize->add_setting( 'prdrwndn_tagline', [
        'default'           => 'A contemporary cultural brand rooted in memory, place and pride.',
        'sanitize_callback' => 'sanitize_textarea_field',
        'transport'         => 'postMessage', // updates live without page reload
    ] );
    $wp_customize->add_control( 'prdrwndn_tagline', [
        'label'       => __( 'Hero Tagline', 'prdrwndn' ),
        'description' => __( 'Short brand sentence shown below the hero headline.', 'prdrwndn' ),
        'section'     => 'prdrwndn_branding',
        'type'        => 'textarea',
    ] );


    /* ── SECTION: Colors ──
       Each color updates a CSS variable across the whole site.
       Use any valid hex color, e.g. #20AA54               */
    $wp_customize->add_section( 'prdrwndn_colors', [
        'title'       => __( 'Colors', 'prdrwndn' ),
        'description' => __( 'Change brand colors. Updates apply site-wide.', 'prdrwndn' ),
        'panel'       => 'prdrwndn_panel',
    ] );

    // Define each color setting — id, default hex, label, description
    $color_settings = [
        'prdrwndn_green'  => [
            'default' => '#20AA54',
            'label'   => 'Brand Green',
            'desc'    => 'Main green — buttons, accents, links, price labels.',
        ],
        'prdrwndn_forest' => [
            'default' => '#1E3B2F',
            'label'   => 'Forest Green',
            'desc'    => 'Deep green used in hero, editorial, and footer backgrounds.',
        ],
        'prdrwndn_cream'  => [
            'default' => '#E8E2D5',
            'label'   => 'Cream',
            'desc'    => 'Warm off-white used for headings and logo text.',
        ],
        'prdrwndn_ink'    => [
            'default' => '#080808',
            'label'   => 'Background Ink',
            'desc'    => 'Main page background color. Keep dark for brand consistency.',
        ],
    ];

    foreach ( $color_settings as $id => $args ) {
        $wp_customize->add_setting( $id, [
            'default'           => $args['default'],
            'sanitize_callback' => 'sanitize_hex_color',
            'transport'         => 'postMessage',
        ] );
        $wp_customize->add_control(
            new WP_Customize_Color_Control( $wp_customize, $id, [
                'label'       => __( $args['label'], 'prdrwndn' ),
                'description' => __( $args['desc'], 'prdrwndn' ),
                'section'     => 'prdrwndn_colors',
            ] )
        );
    }


    /* ── SECTION: Homepage ──
       Controls text and product selection on the homepage. */
    $wp_customize->add_section( 'prdrwndn_homepage', [
        'title'       => __( 'Homepage', 'prdrwndn' ),
        'description' => __( 'Control the homepage hero text and which products appear.', 'prdrwndn' ),
        'panel'       => 'prdrwndn_panel',
    ] );

    // Hero headline — line 1 (white text)
    $wp_customize->add_setting( 'prdrwndn_hero_line1', [
        'default'           => 'YOUR ROOTS.',
        'sanitize_callback' => 'sanitize_text_field',
        'transport'         => 'postMessage',
    ] );
    $wp_customize->add_control( 'prdrwndn_hero_line1', [
        'label'       => __( 'Hero Headline — Line 1', 'prdrwndn' ),
        'description' => __( 'First line of the big hero headline (cream/white).', 'prdrwndn' ),
        'section'     => 'prdrwndn_homepage',
    ] );

    // Hero headline — line 2 (green accent text)
    $wp_customize->add_setting( 'prdrwndn_hero_line2', [
        'default'           => 'YOUR HOME.',
        'sanitize_callback' => 'sanitize_text_field',
        'transport'         => 'postMessage',
    ] );
    $wp_customize->add_control( 'prdrwndn_hero_line2', [
        'label'       => __( 'Hero Headline — Line 2 (green accent)', 'prdrwndn' ),
        'description' => __( 'Second line shown in brand green color.', 'prdrwndn' ),
        'section'     => 'prdrwndn_homepage',
    ] );

    // Featured freshener product ID
    // To find a product ID: go to Products → hover product → see ?post=NUMBER in URL
    $wp_customize->add_setting( 'prdrwndn_freshener_id', [
        'default'           => '',
        'sanitize_callback' => 'absint', // ensures it's a whole number
    ] );
    $wp_customize->add_control( 'prdrwndn_freshener_id', [
        'label'       => __( 'Featured Freshener — Product ID', 'prdrwndn' ),
        'description' => __( 'Enter the WooCommerce product ID for the car freshener spotlight. Find it in Products → hover the product → look for "post=NUMBER" in the URL.', 'prdrwndn' ),
        'section'     => 'prdrwndn_homepage',
        'type'        => 'number',
    ] );

    // How many secondary products to show below the freshener spotlight
    $wp_customize->add_setting( 'prdrwndn_products_count', [
        'default'           => '4',
        'sanitize_callback' => 'absint',
    ] );
    $wp_customize->add_control( 'prdrwndn_products_count', [
        'label'       => __( 'Number of Secondary Products', 'prdrwndn' ),
        'description' => __( 'How many products to show in the "Home Collection" grid below the freshener spotlight.', 'prdrwndn' ),
        'section'     => 'prdrwndn_homepage',
        'type'        => 'number',
    ] );


    /* ── SECTION: Footer ── */
    $wp_customize->add_section( 'prdrwndn_footer', [
        'title'       => __( 'Footer', 'prdrwndn' ),
        'description' => __( 'Customize the footer brand description.', 'prdrwndn' ),
        'panel'       => 'prdrwndn_panel',
    ] );

    // Footer brand description — the paragraph under the logo in the footer
    $wp_customize->add_setting( 'prdrwndn_footer_desc', [
        'default'           => 'Shop your roots. Rwanda map-shaped car fresheners, heritage apparel, and cultural pride — for the global Rwandan community.',
        'sanitize_callback' => 'sanitize_textarea_field',
        'transport'         => 'postMessage',
    ] );
    $wp_customize->add_control( 'prdrwndn_footer_desc', [
        'label'       => __( 'Footer Brand Description', 'prdrwndn' ),
        'description' => __( 'Short paragraph shown under the PRDRWNDN® logo in the footer.', 'prdrwndn' ),
        'section'     => 'prdrwndn_footer',
        'type'        => 'textarea',
    ] );
}
add_action( 'customize_register', 'prdrwndn_customizer' );


/**
 * Output customizer color choices as CSS variables.
 * This runs on every page load and injects a <style> tag
 * with the colors the user picked in the Customizer.
 */
function prdrwndn_customizer_css() {
    $green  = get_theme_mod( 'prdrwndn_green',  '#20AA54' );
    $forest = get_theme_mod( 'prdrwndn_forest', '#1E3B2F' );
    $cream  = get_theme_mod( 'prdrwndn_cream',  '#E8E2D5' );
    $ink    = get_theme_mod( 'prdrwndn_ink',    '#080808' );
    echo "<style id='prdrwndn-customizer-vars'>:root {
        --rw-green:  {$green};
        --rw-green3: {$forest};
        --rw-cream:  {$cream};
        --ink:       {$ink};
    }</style>";
}
add_action( 'wp_head', 'prdrwndn_customizer_css' );


/* ════════════════════════════════════════════════════
   6. HELPER FUNCTIONS
   Small reusable functions called from template files.
   You can call these anywhere in a PHP template file.
════════════════════════════════════════════════════ */

/**
 * Get the featured car freshener product.
 *
 * First checks the Customizer setting (Freshener Product ID).
 * If not set, falls back to searching for a product with
 * "freshener" in the name.
 *
 * @return WC_Product|null  The product object, or null if not found.
 */
function prdrwndn_get_freshener() {
    $id = (int) get_theme_mod( 'prdrwndn_freshener_id', 0 );

    // Use the specific product ID if set in Customizer
    if ( $id > 0 ) {
        return wc_get_product( $id );
    }

    // Fallback: find any product with "freshener" in its name
    $query = new WP_Query( [
        'post_type'      => 'product',
        'posts_per_page' => 1,
        's'              => 'freshener',
        'post_status'    => 'publish',
    ] );
    if ( $query->have_posts() ) {
        $query->the_post();
        $product = wc_get_product( get_the_ID() );
        wp_reset_postdata();
        return $product;
    }

    return null; // No freshener found
}


/**
 * Render the Rwanda flag stripe (green / yellow / blue bar).
 * Call this in any template: <?php prdrwndn_flag_stripe(); ?>
 *
 * @param string $class  Optional extra CSS class.
 */
function prdrwndn_flag_stripe( $class = '' ) {
    $class = $class ? ' ' . esc_attr( $class ) : '';
    echo '<div class="flag-stripe' . $class . '" aria-hidden="true"></div>';
}


/**
 * Return a string of filled star characters.
 * Used for review star ratings.
 *
 * @param  int    $count  Number of stars (default 5).
 * @return string         e.g. "★★★★★"
 */
function prdrwndn_stars( $count = 5 ) {
    return str_repeat( '★', max( 0, min( 5, (int) $count ) ) );
}


/* ════════════════════════════════════════════════════
   7. PWA — PROGRESSIVE WEB APP
   Adds the manifest link and service worker registration
   to every page on the site so it can be installed
   as a home screen app.

   Required files in your WordPress root (public_html/):
   - manifest.json       (already created)
   - service-worker.js   (already created)
   - app.html            (already created)
════════════════════════════════════════════════════ */

/**
 * Add PWA meta tags and manifest link to <head>.
 * This is what tells browsers the site is installable.
 */
function prdrwndn_pwa_head() { ?>
    <link rel="manifest" href="<?php echo esc_url( home_url( '/manifest.json' ) ); ?>"/>
    <meta name="theme-color" content="#20AA54"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-title" content="PRDRWNDN"/>
    <link rel="apple-touch-icon" href="<?php echo esc_url( home_url( '/wp-content/uploads/2025/12/cropped-IMG_2191-270x270.png' ) ); ?>"/>
<?php }
add_action( 'wp_head', 'prdrwndn_pwa_head' );


/**
 * Register the service worker via JavaScript.
 * Runs after the page loads so it doesn't slow anything down.
 */
function prdrwndn_pwa_footer() { ?>
<script>
if ('serviceWorker' in navigator) {
    window.addEventListener('load', function() {
        navigator.serviceWorker
            .register('/service-worker.js', { scope: '/' })
            .then(function(r) { console.log('[PRDRWNDN] SW registered:', r.scope); })
            .catch(function(e) { console.warn('[PRDRWNDN] SW failed:', e); });
    });
}
</script>
<?php }
add_action( 'wp_footer', 'prdrwndn_pwa_footer' );


/* ════════════════════════════════════════════════════
   8. AJAX — CART COUNT
   Returns the current WooCommerce cart item count
   as plain text. Called by JavaScript to update the
   cart badge in the header without a page reload.

   URL: /wp-admin/admin-ajax.php?action=prdrwndn_cart_count
════════════════════════════════════════════════════ */
function prdrwndn_cart_count() {
    if ( class_exists( 'WooCommerce' ) ) {
        echo absint( WC()->cart->get_cart_contents_count() );
    } else {
        echo '0';
    }
    wp_die(); // Always end AJAX handlers with wp_die()
}
// Register for both logged-in and logged-out users
add_action( 'wp_ajax_prdrwndn_cart_count',        'prdrwndn_cart_count' );
add_action( 'wp_ajax_nopriv_prdrwndn_cart_count', 'prdrwndn_cart_count' );


/* ════════════════════════════════════════════════════
   9. GUTENBERG — DISABLE ON CUSTOM TEMPLATES
   Our custom page templates (homepage, about, collection)
   use their own PHP layouts. We disable the block editor
   on these pages because it would conflict with our code.
   You can still use the block editor on regular pages.
════════════════════════════════════════════════════ */
function prdrwndn_disable_gutenberg( $use_block_editor, $post ) {
    // List of our custom template files
    $custom_templates = [
        'front-page.php',
        'page-about.php',
        'page-collection.php',
    ];
    $template = get_post_meta( $post->ID, '_wp_page_template', true );
    if ( in_array( $template, $custom_templates, true ) ) {
        return false; // Use classic editor instead
    }
    return $use_block_editor;
}
add_filter( 'use_block_editor_for_post', 'prdrwndn_disable_gutenberg', 10, 2 );


/* ════════════════════════════════════════════════════
   GITHUB AUTO-UPDATER
   Checks GitHub for new theme versions and shows
   an "Update Available" notice in WordPress dashboard
   just like a regular theme update.

   HOW IT WORKS:
   1. You push changes to GitHub
   2. You create a new Release and tag it (e.g. v1.1.0)
   3. WordPress checks GitHub and shows update available
   4. You click "Update" — done, just like WordPress core

   SETUP REQUIRED:
   - Set PRDRWNDN_GITHUB_REPO to your GitHub username/repo
   - Set PRDRWNDN_GITHUB_TOKEN if your repo is private
════════════════════════════════════════════════════ */

// ── YOUR GITHUB SETTINGS ──────────────────────────
// Change this to your GitHub repo after creating it
define( 'PRDRWNDN_GITHUB_REPO',  'isshiimwe/prdrwndn-theme' );
define( 'PRDRWNDN_GITHUB_TOKEN', '' ); // Leave empty for public repo
// ──────────────────────────────────────────────────

/**
 * Check GitHub for a newer version of the theme.
 * WordPress calls this automatically in the background.
 */
function prdrwndn_check_for_update( $transient ) {
    if ( empty( $transient->checked ) ) return $transient;

    $theme_slug    = 'prdrwndn-theme';
    $current_ver   = wp_get_theme( $theme_slug )->get( 'Version' );
    $github_repo   = PRDRWNDN_GITHUB_REPO;
    $github_token  = PRDRWNDN_GITHUB_TOKEN;

    // Only check every 12 hours to avoid API rate limits
    $cache_key = 'prdrwndn_github_update_' . $theme_slug;
    $cached    = get_transient( $cache_key );

    if ( false === $cached ) {
        // Fetch latest release from GitHub API
        $url  = "https://api.github.com/repos/{$github_repo}/releases/latest";
        $args = [
            'headers' => [
                'User-Agent' => 'WordPress/' . get_bloginfo('version'),
                'Accept'     => 'application/vnd.github.v3+json',
            ],
            'timeout' => 10,
        ];

        // Add auth header for private repos
        if ( ! empty( $github_token ) ) {
            $args['headers']['Authorization'] = "token {$github_token}";
        }

        $response = wp_remote_get( $url, $args );

        if ( is_wp_error( $response ) ) return $transient;
        if ( 200 !== wp_remote_retrieve_response_code( $response ) ) return $transient;

        $release = json_decode( wp_remote_retrieve_body( $response ) );
        if ( empty( $release->tag_name ) ) return $transient;

        // Cache for 12 hours
        set_transient( $cache_key, $release, 12 * HOUR_IN_SECONDS );
        $cached = $release;
    }

    // Strip 'v' prefix from tag (v1.1.0 → 1.1.0)
    $latest_ver = ltrim( $cached->tag_name, 'v' );

    // If GitHub has a newer version, tell WordPress about it
    if ( version_compare( $latest_ver, $current_ver, '>' ) ) {

        // Find the ATTACHED zip asset — must be named prdrwndn-theme.zip
        $zip_url = '';
        if ( ! empty( $cached->assets ) ) {
            foreach ( $cached->assets as $asset ) {
                if ( str_ends_with( $asset->name, '.zip' ) ) {
                    $zip_url = $asset->browser_download_url;
                    break;
                }
            }
        }

        // NEVER use auto-generated zip — wrong folder name breaks WordPress
        if ( empty( $zip_url ) ) {
            return $transient; // Skip — no attached zip found
        }

        $transient->response[ $theme_slug ] = [
            'theme'       => $theme_slug,
            'new_version' => $latest_ver,
            'url'         => "https://github.com/{$github_repo}",
            'package'     => $zip_url,
        ];
    }

    return $transient;
}
add_filter( 'pre_set_site_transient_update_themes', 'prdrwndn_check_for_update' );


/**
 * Clear the GitHub update cache when WordPress
 * manually triggers a theme update check.
 */
function prdrwndn_clear_update_cache() {
    delete_transient( 'prdrwndn_github_update_prdrwndn-theme' );
}
add_action( 'upgrader_process_complete', 'prdrwndn_clear_update_cache' );


/**
 * Show a notice in the WordPress dashboard if the
 * GitHub repo hasn't been configured yet.
 */
function prdrwndn_github_setup_notice() {
    if ( PRDRWNDN_GITHUB_REPO !== 'YOUR-USERNAME/prdrwndn-theme' ) return;
    if ( ! current_user_can( 'manage_options' ) ) return;
    $screen = get_current_screen();
    if ( ! $screen || $screen->id !== 'themes' ) return;
    ?>
    <div class="notice notice-warning">
        <p>
            <strong>PRDRWNDN® Theme:</strong>
            GitHub auto-updates are not configured yet.
            Open <code>wp-content/themes/prdrwndn-theme/functions.php</code>
            and set <code>PRDRWNDN_GITHUB_REPO</code> to your GitHub repository.
        </p>
    </div>
    <?php
}
add_action( 'admin_notices', 'prdrwndn_github_setup_notice' );


/* ════════════════════════════════════════════════════
   FORCE SHOP ARCHIVE TEMPLATE
   Ensures WooCommerce uses our archive-product.php
   for the shop page instead of the generic wrapper
════════════════════════════════════════════════════ */
function prdrwndn_shop_template( $template ) {
    if ( is_shop() || is_product_category() || is_product_tag() ) {
        $custom = get_template_directory() . '/woocommerce/archive-product.php';
        if ( file_exists( $custom ) ) {
            return $custom;
        }
    }
    return $template;
}
add_filter( 'template_include', 'prdrwndn_shop_template', 99 );
